INSERT INTO public.exercises (name, muscle_group, equipment, is_public) VALUES
  ('Bent Over Row (Dumbbell)', 'back', 'dumbbell', true),
  ('Bicep Curl (Dumbbell)', 'biceps', 'dumbbell', true),
  ('Chest Press (Band)', 'chest', 'band', true),
  ('Concentration Curl', 'biceps', 'other', true),
  ('Deadlift (Dumbbell)', 'back', 'dumbbell', true),
  ('Deadlift High Pull', 'back', 'other', true),
  ('Decline Push Up', 'full_body', 'bodyweight', true),
  ('Floor Press (Barbell)', 'chest', 'barbell', true),
  ('Floor Press (Dumbbell)', 'chest', 'dumbbell', true),
  ('Kettlebell Around the World', 'full_body', 'kettlebell', true),
  ('Kettlebell Curl', 'biceps', 'kettlebell', true),
  ('Kettlebell Goblet Squat', 'legs', 'kettlebell', true),
  ('Kettlebell Halo', 'full_body', 'kettlebell', true),
  ('Kettlebell High Pull', 'back', 'kettlebell', true),
  ('Kneeling Pulldown (band)', 'back', 'band', true),
  ('Lunge (Dumbbell)', 'legs', 'dumbbell', true),
  ('Lying Leg Raise', 'legs', 'other', true),
  ('Overhead Press (Dumbbell)', 'shoulders', 'dumbbell', true),
  ('Pullover (Dumbbell)', 'back', 'dumbbell', true),
  ('Russian Twist (Weighted)', 'full_body', 'other', true),
  ('Shrug (Dumbbell)', 'full_body', 'dumbbell', true),
  ('Split Squat (Dumbbell)', 'legs', 'dumbbell', true),
  ('Squat (Dumbbell)', 'legs', 'dumbbell', true),
  ('Thruster (Kettlebell)', 'full_body', 'kettlebell', true),
  ('Treadmill', 'full_body', 'other', true),
  ('Triceps Dip', 'triceps', 'bodyweight', true),
  ('Jump Rope', 'cardio', 'bodyweight', true);
