version = 3

[global]

[auth]
version = "0.41.0"

[auth.redirections]
clientUrl = "http://localhost:5173"

[auth.session]
accessToken = { expiresIn = 900 }
refreshToken = { expiresIn = 2592000 }

[postgres]
version = "17.0"

[postgres.resources]
enablePublicAccess = true

[graphql]
version = "v2.46.0"

[storage]
version = "0.7.0"

[functions]
[hasura]
version = "v2.46.0"
