INSERT INTO public.exercises (name, muscle_group, equipment, is_public) VALUES
  ('Warm Up', 'full_body', 'bodyweight', true),
  ('Deadlift (Barbell)', 'back', 'barbell', true),
  ('Bent Over Row (Barbell)', 'back', 'barbell', true),
  ('Lateral Raise (Dumbbell)', 'shoulders', 'dumbbell', true),
  ('EZ Bar Biceps Curl', 'biceps', 'barbell', true),
  ('Skullcrusher (Dumbbell)', 'triceps', 'dumbbell', true),
  ('Crunch (Weighted)', 'abs', 'bodyweight', true),
  ('Pull Up', 'back', 'bodyweight', true),
  ('Squat (Barbell)', 'legs', 'barbell', true),
  ('Bench Press (Barbell)', 'chest', 'barbell', true),
  ('Overhead Press (Barbell)', 'shoulders', 'barbell', true),
  ('Romanian Deadlift (Barbell)', 'legs', 'barbell', true),
  ('Leg Press', 'legs', 'machine', true),
  ('Lat Pulldown (Cable)', 'back', 'cable', true),
  ('Seated Row (Cable)', 'back', 'cable', true),
  ('Chest Fly (Dumbbell)', 'chest', 'dumbbell', true),
  ('Incline Bench Press (Barbell)', 'chest', 'barbell', true),
  ('Dumbbell Bench Press', 'chest', 'dumbbell', true),
  ('Triceps Pushdown (Cable)', 'triceps', 'cable', true),
  ('Hammer Curl (Dumbbell)', 'biceps', 'dumbbell', true),
  ('Face Pull (Cable)', 'shoulders', 'cable', true),
  ('Leg Curl (Machine)', 'legs', 'machine', true),
  ('Leg Extension (Machine)', 'legs', 'machine', true),
  ('Calf Raise (Machine)', 'legs', 'machine', true),
  ('Hip Thrust (Barbell)', 'legs', 'barbell', true),
  ('Bulgarian Split Squat (Dumbbell)', 'legs', 'dumbbell', true),
  ('Goblet Squat (Dumbbell)', 'legs', 'dumbbell', true),
  ('Front Squat (Barbell)', 'legs', 'barbell', true),
  ('Sumo Deadlift (Barbell)', 'legs', 'barbell', true),
  ('Chin Up', 'back', 'bodyweight', true),
  ('Dip', 'chest', 'bodyweight', true),
  ('Push Up', 'chest', 'bodyweight', true),
  ('Plank', 'abs', 'bodyweight', true),
  ('Hanging Leg Raise', 'abs', 'bodyweight', true),
  ('Cable Crunch', 'abs', 'cable', true),
  ('Shrug (Barbell)', 'back', 'barbell', true),
  ('Farmer Walk (Dumbbell)', 'full_body', 'dumbbell', true),
  ('Kettlebell Swing', 'full_body', 'kettlebell', true),
  ('Box Jump', 'legs', 'bodyweight', true),
  ('Running', 'cardio', 'bodyweight', true),
  ('Cycling', 'cardio', 'machine', true),
  ('Rowing (Machine)', 'cardio', 'machine', true),
  ('Arnold Press (Dumbbell)', 'shoulders', 'dumbbell', true),
  ('Reverse Fly (Dumbbell)', 'shoulders', 'dumbbell', true),
  ('Preacher Curl (Barbell)', 'biceps', 'barbell', true),
  ('Close Grip Bench Press (Barbell)', 'triceps', 'barbell', true),
  ('Good Morning (Barbell)', 'back', 'barbell', true),
  ('Hack Squat (Machine)', 'legs', 'machine', true),
  ('T-Bar Row', 'back', 'barbell', true),
  ('Cable Lateral Raise', 'shoulders', 'cable', true),
  ('Decline Bench Press (Barbell)', 'chest', 'barbell', true),
  ('Pec Deck (Machine)', 'chest', 'machine', true),
  ('Back Extension', 'back', 'bodyweight', true);
