export function normalizeOcrText(text: string): string {
  return text
    .normalize('NFC')
    .replace(/\r/g, '\n')
    .replace(/[|]/g, ' ')
    .replace(/[’‘`´]/g, "'")
    .replace(/dontacides/gi, 'dont acides')
    .replace(/dont\s*acides/gi, 'dont acides')
    .replace(/dontsucres(\d)/gi, 'dont sucres $1')
    .replace(/dontsucres/gi, 'dont sucres')
    .replace(/dont\s*sucres/gi, 'dont sucres')
    .replace(/\bjucides\b/gi, 'Glucides')
    .replace(/\bgiucides\b/gi, 'Glucides')
    .replace(/\bfoteines\b/gi, 'Protéines')
    .replace(/\bprot[eé]ines\b/gi, 'Protéines')
    .replace(/\bmatieres\b/gi, 'matières')
    .replace(/\bmatiéres\b/gi, 'matières')
    .replace(/\bénergie\b/gi, 'énergie')
    .replace(/(\d)\s*kcal/gi, '$1 kcal')
    .replace(/(\d)\s*kJ/gi, '$1 kJ')
    .replace(/(\d)\s*g\b/gi, '$1 g')
    .replace(/\bOg\b/g, '0 g')
    .replace(/\bOu\b/g, '0 g')
    .replace(/:\s*0g\b/gi, ': 0 g')
}
