/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoachRouteRouteImport } from './routes/coach/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app/workouts/index'
import { Route as AppExercisesIndexRouteImport } from './routes/app/exercises/index'
import { Route as AppWorkoutActiveRouteImport } from './routes/app/workout/active'

const CoachRouteRoute = CoachRouteRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExercisesIndexRoute = AppExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutActiveRoute = AppWorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stats': typeof AppStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/exercises/': typeof AppExercisesIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/import': typeof AppImportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stats': typeof AppStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/coach': typeof CoachIndexRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/exercises': typeof AppExercisesIndexRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/stats': typeof AppStatsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/exercises/': typeof AppExercisesIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/coach'
    | '/app/import'
    | '/app/profile'
    | '/app/stats'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/coach/'
    | '/app/workout/active'
    | '/app/exercises/'
    | '/app/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/import'
    | '/app/profile'
    | '/app/stats'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/coach'
    | '/app/workout/active'
    | '/app/exercises'
    | '/app/workouts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/coach'
    | '/app/import'
    | '/app/profile'
    | '/app/stats'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/coach/'
    | '/app/workout/active'
    | '/app/exercises/'
    | '/app/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CoachRouteRoute: typeof CoachRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/exercises/': {
      id: '/app/exercises/'
      path: '/exercises'
      fullPath: '/app/exercises/'
      preLoaderRoute: typeof AppExercisesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workout/active': {
      id: '/app/workout/active'
      path: '/workout/active'
      fullPath: '/app/workout/active'
      preLoaderRoute: typeof AppWorkoutActiveRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkoutActiveRoute: typeof AppWorkoutActiveRoute
  AppExercisesIndexRoute: typeof AppExercisesIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppProfileRoute: AppProfileRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkoutActiveRoute: AppWorkoutActiveRoute,
  AppExercisesIndexRoute: AppExercisesIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CoachRouteRouteChildren {
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteRouteChildren: CoachRouteRouteChildren = {
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteRouteWithChildren = CoachRouteRoute._addFileChildren(
  CoachRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CoachRouteRoute: CoachRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
