/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoachRouteRouteImport } from './routes/coach/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppImportRouteImport } from './routes/app/import'
import { Route as AppProfileRouteRouteImport } from './routes/app/profile/route'
import { Route as CoachValidateProductRenamesIndexRouteImport } from './routes/coach/validate-product-renames/index'
import { Route as CoachProgramsIndexRouteImport } from './routes/coach/programs/index'
import { Route as CoachClientsIndexRouteImport } from './routes/coach/clients/index'
import { Route as CoachAnalyticsIndexRouteImport } from './routes/coach/analytics/index'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app/workouts/index'
import { Route as AppSessionsIndexRouteImport } from './routes/app/sessions/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppPremiumIndexRouteImport } from './routes/app/premium/index'
import { Route as AppPlanningIndexRouteImport } from './routes/app/planning/index'
import { Route as AppGoalsIndexRouteImport } from './routes/app/goals/index'
import { Route as AppFriendsIndexRouteImport } from './routes/app/friends/index'
import { Route as AppExercisesIndexRouteImport } from './routes/app/exercises/index'
import { Route as AppDietIndexRouteImport } from './routes/app/diet/index'
import { Route as ShareWorkoutShareTokenRouteImport } from './routes/share/workout/$shareToken'
import { Route as CoachProgramsProgramIdRouteImport } from './routes/coach/programs/$programId'
import { Route as AppWorkoutsWorkoutIdRouteImport } from './routes/app/workouts/$workoutId'
import { Route as AppWorkoutActiveRouteImport } from './routes/app/workout/active'
import { Route as AppSessionsNewRouteImport } from './routes/app/sessions/new'
import { Route as AppSessionsTemplateIdRouteImport } from './routes/app/sessions/$templateId'
import { Route as AppProfileSettingsRouteImport } from './routes/app/profile/settings'
import { Route as AppDietSettingsRouteImport } from './routes/app/diet/settings'
import { Route as AppDietAddRouteImport } from './routes/app/diet/add'
import { Route as AppStatsExercisesExerciseIdRouteImport } from './routes/app/stats/exercises/$exerciseId'
import { Route as AppDietMealsMealTypeRouteImport } from './routes/app/diet/meals/$mealType'
import { Route as AppDietFoodsNewRouteImport } from './routes/app/diet/foods/new'

const CoachRouteRoute = CoachRouteRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const CoachValidateProductRenamesIndexRoute =
  CoachValidateProductRenamesIndexRouteImport.update({
    id: '/validate-product-renames/',
    path: '/validate-product-renames/',
    getParentRoute: () => CoachRouteRoute,
  } as any)
const CoachProgramsIndexRoute = CoachProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachClientsIndexRoute = CoachClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachAnalyticsIndexRoute = CoachAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppPremiumIndexRoute = AppPremiumIndexRouteImport.update({
  id: '/premium/',
  path: '/premium/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanningIndexRoute = AppPlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsIndexRoute = AppFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExercisesIndexRoute = AppExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDietIndexRoute = AppDietIndexRouteImport.update({
  id: '/diet/',
  path: '/diet/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareWorkoutShareTokenRoute = ShareWorkoutShareTokenRouteImport.update({
  id: '/share/workout/$shareToken',
  path: '/share/workout/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramsProgramIdRoute = CoachProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => CoachRouteRoute,
} as any)
const AppWorkoutsWorkoutIdRoute = AppWorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutActiveRoute = AppWorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessionsTemplateIdRoute = AppSessionsTemplateIdRouteImport.update({
  id: '/sessions/$templateId',
  path: '/sessions/$templateId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileSettingsRoute = AppProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProfileRouteRoute,
} as any)
const AppDietSettingsRoute = AppDietSettingsRouteImport.update({
  id: '/diet/settings',
  path: '/diet/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDietAddRoute = AppDietAddRouteImport.update({
  id: '/diet/add',
  path: '/diet/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatsExercisesExerciseIdRoute =
  AppStatsExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => AppStatsRoute,
  } as any)
const AppDietMealsMealTypeRoute = AppDietMealsMealTypeRouteImport.update({
  id: '/diet/meals/$mealType',
  path: '/diet/meals/$mealType',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDietFoodsNewRoute = AppDietFoodsNewRouteImport.update({
  id: '/diet/foods/new',
  path: '/diet/foods/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/stats': typeof AppStatsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/diet/add': typeof AppDietAddRoute
  '/app/diet/settings': typeof AppDietSettingsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/sessions/$templateId': typeof AppSessionsTemplateIdRoute
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRoute
  '/share/workout/$shareToken': typeof ShareWorkoutShareTokenRoute
  '/app/diet/': typeof AppDietIndexRoute
  '/app/exercises/': typeof AppExercisesIndexRoute
  '/app/friends/': typeof AppFriendsIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/planning/': typeof AppPlanningIndexRoute
  '/app/premium/': typeof AppPremiumIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/coach/analytics/': typeof CoachAnalyticsIndexRoute
  '/coach/clients/': typeof CoachClientsIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/validate-product-renames/': typeof CoachValidateProductRenamesIndexRoute
  '/app/diet/foods/new': typeof AppDietFoodsNewRoute
  '/app/diet/meals/$mealType': typeof AppDietMealsMealTypeRoute
  '/app/stats/exercises/$exerciseId': typeof AppStatsExercisesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/import': typeof AppImportRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/stats': typeof AppStatsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app': typeof AppIndexRoute
  '/coach': typeof CoachIndexRoute
  '/app/diet/add': typeof AppDietAddRoute
  '/app/diet/settings': typeof AppDietSettingsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/sessions/$templateId': typeof AppSessionsTemplateIdRoute
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRoute
  '/share/workout/$shareToken': typeof ShareWorkoutShareTokenRoute
  '/app/diet': typeof AppDietIndexRoute
  '/app/exercises': typeof AppExercisesIndexRoute
  '/app/friends': typeof AppFriendsIndexRoute
  '/app/goals': typeof AppGoalsIndexRoute
  '/app/planning': typeof AppPlanningIndexRoute
  '/app/premium': typeof AppPremiumIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/sessions': typeof AppSessionsIndexRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
  '/coach/analytics': typeof CoachAnalyticsIndexRoute
  '/coach/clients': typeof CoachClientsIndexRoute
  '/coach/programs': typeof CoachProgramsIndexRoute
  '/coach/validate-product-renames': typeof CoachValidateProductRenamesIndexRoute
  '/app/diet/foods/new': typeof AppDietFoodsNewRoute
  '/app/diet/meals/$mealType': typeof AppDietMealsMealTypeRoute
  '/app/stats/exercises/$exerciseId': typeof AppStatsExercisesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/app/profile': typeof AppProfileRouteRouteWithChildren
  '/app/import': typeof AppImportRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/stats': typeof AppStatsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/app/diet/add': typeof AppDietAddRoute
  '/app/diet/settings': typeof AppDietSettingsRoute
  '/app/profile/settings': typeof AppProfileSettingsRoute
  '/app/sessions/$templateId': typeof AppSessionsTemplateIdRoute
  '/app/sessions/new': typeof AppSessionsNewRoute
  '/app/workout/active': typeof AppWorkoutActiveRoute
  '/app/workouts/$workoutId': typeof AppWorkoutsWorkoutIdRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRoute
  '/share/workout/$shareToken': typeof ShareWorkoutShareTokenRoute
  '/app/diet/': typeof AppDietIndexRoute
  '/app/exercises/': typeof AppExercisesIndexRoute
  '/app/friends/': typeof AppFriendsIndexRoute
  '/app/goals/': typeof AppGoalsIndexRoute
  '/app/planning/': typeof AppPlanningIndexRoute
  '/app/premium/': typeof AppPremiumIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/sessions/': typeof AppSessionsIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/coach/analytics/': typeof CoachAnalyticsIndexRoute
  '/coach/clients/': typeof CoachClientsIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/validate-product-renames/': typeof CoachValidateProductRenamesIndexRoute
  '/app/diet/foods/new': typeof AppDietFoodsNewRoute
  '/app/diet/meals/$mealType': typeof AppDietMealsMealTypeRoute
  '/app/stats/exercises/$exerciseId': typeof AppStatsExercisesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/coach'
    | '/app/profile'
    | '/app/import'
    | '/app/onboarding'
    | '/app/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/app/'
    | '/coach/'
    | '/app/diet/add'
    | '/app/diet/settings'
    | '/app/profile/settings'
    | '/app/sessions/$templateId'
    | '/app/sessions/new'
    | '/app/workout/active'
    | '/app/workouts/$workoutId'
    | '/coach/programs/$programId'
    | '/share/workout/$shareToken'
    | '/app/diet/'
    | '/app/exercises/'
    | '/app/friends/'
    | '/app/goals/'
    | '/app/planning/'
    | '/app/premium/'
    | '/app/profile/'
    | '/app/sessions/'
    | '/app/workouts/'
    | '/coach/analytics/'
    | '/coach/clients/'
    | '/coach/programs/'
    | '/coach/validate-product-renames/'
    | '/app/diet/foods/new'
    | '/app/diet/meals/$mealType'
    | '/app/stats/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/import'
    | '/app/onboarding'
    | '/app/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/app'
    | '/coach'
    | '/app/diet/add'
    | '/app/diet/settings'
    | '/app/profile/settings'
    | '/app/sessions/$templateId'
    | '/app/sessions/new'
    | '/app/workout/active'
    | '/app/workouts/$workoutId'
    | '/coach/programs/$programId'
    | '/share/workout/$shareToken'
    | '/app/diet'
    | '/app/exercises'
    | '/app/friends'
    | '/app/goals'
    | '/app/planning'
    | '/app/premium'
    | '/app/profile'
    | '/app/sessions'
    | '/app/workouts'
    | '/coach/analytics'
    | '/coach/clients'
    | '/coach/programs'
    | '/coach/validate-product-renames'
    | '/app/diet/foods/new'
    | '/app/diet/meals/$mealType'
    | '/app/stats/exercises/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/coach'
    | '/app/profile'
    | '/app/import'
    | '/app/onboarding'
    | '/app/stats'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/app/'
    | '/coach/'
    | '/app/diet/add'
    | '/app/diet/settings'
    | '/app/profile/settings'
    | '/app/sessions/$templateId'
    | '/app/sessions/new'
    | '/app/workout/active'
    | '/app/workouts/$workoutId'
    | '/coach/programs/$programId'
    | '/share/workout/$shareToken'
    | '/app/diet/'
    | '/app/exercises/'
    | '/app/friends/'
    | '/app/goals/'
    | '/app/planning/'
    | '/app/premium/'
    | '/app/profile/'
    | '/app/sessions/'
    | '/app/workouts/'
    | '/coach/analytics/'
    | '/coach/clients/'
    | '/coach/programs/'
    | '/coach/validate-product-renames/'
    | '/app/diet/foods/new'
    | '/app/diet/meals/$mealType'
    | '/app/stats/exercises/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CoachRouteRoute: typeof CoachRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ShareWorkoutShareTokenRoute: typeof ShareWorkoutShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/coach/validate-product-renames/': {
      id: '/coach/validate-product-renames/'
      path: '/validate-product-renames'
      fullPath: '/coach/validate-product-renames/'
      preLoaderRoute: typeof CoachValidateProductRenamesIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/programs/': {
      id: '/coach/programs/'
      path: '/programs'
      fullPath: '/coach/programs/'
      preLoaderRoute: typeof CoachProgramsIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/clients/': {
      id: '/coach/clients/'
      path: '/clients'
      fullPath: '/coach/clients/'
      preLoaderRoute: typeof CoachClientsIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/analytics/': {
      id: '/coach/analytics/'
      path: '/analytics'
      fullPath: '/coach/analytics/'
      preLoaderRoute: typeof CoachAnalyticsIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessions/': {
      id: '/app/sessions/'
      path: '/sessions'
      fullPath: '/app/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/premium/': {
      id: '/app/premium/'
      path: '/premium'
      fullPath: '/app/premium/'
      preLoaderRoute: typeof AppPremiumIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/planning/': {
      id: '/app/planning/'
      path: '/planning'
      fullPath: '/app/planning/'
      preLoaderRoute: typeof AppPlanningIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/goals/': {
      id: '/app/goals/'
      path: '/goals'
      fullPath: '/app/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends/': {
      id: '/app/friends/'
      path: '/friends'
      fullPath: '/app/friends/'
      preLoaderRoute: typeof AppFriendsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/exercises/': {
      id: '/app/exercises/'
      path: '/exercises'
      fullPath: '/app/exercises/'
      preLoaderRoute: typeof AppExercisesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/diet/': {
      id: '/app/diet/'
      path: '/diet'
      fullPath: '/app/diet/'
      preLoaderRoute: typeof AppDietIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/workout/$shareToken': {
      id: '/share/workout/$shareToken'
      path: '/share/workout/$shareToken'
      fullPath: '/share/workout/$shareToken'
      preLoaderRoute: typeof ShareWorkoutShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/programs/$programId': {
      id: '/coach/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/coach/programs/$programId'
      preLoaderRoute: typeof CoachProgramsProgramIdRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/app/workouts/$workoutId': {
      id: '/app/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/app/workouts/$workoutId'
      preLoaderRoute: typeof AppWorkoutsWorkoutIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workout/active': {
      id: '/app/workout/active'
      path: '/workout/active'
      fullPath: '/app/workout/active'
      preLoaderRoute: typeof AppWorkoutActiveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessions/new': {
      id: '/app/sessions/new'
      path: '/sessions/new'
      fullPath: '/app/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessions/$templateId': {
      id: '/app/sessions/$templateId'
      path: '/sessions/$templateId'
      fullPath: '/app/sessions/$templateId'
      preLoaderRoute: typeof AppSessionsTemplateIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile/settings': {
      id: '/app/profile/settings'
      path: '/settings'
      fullPath: '/app/profile/settings'
      preLoaderRoute: typeof AppProfileSettingsRouteImport
      parentRoute: typeof AppProfileRouteRoute
    }
    '/app/diet/settings': {
      id: '/app/diet/settings'
      path: '/diet/settings'
      fullPath: '/app/diet/settings'
      preLoaderRoute: typeof AppDietSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/diet/add': {
      id: '/app/diet/add'
      path: '/diet/add'
      fullPath: '/app/diet/add'
      preLoaderRoute: typeof AppDietAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stats/exercises/$exerciseId': {
      id: '/app/stats/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/app/stats/exercises/$exerciseId'
      preLoaderRoute: typeof AppStatsExercisesExerciseIdRouteImport
      parentRoute: typeof AppStatsRoute
    }
    '/app/diet/meals/$mealType': {
      id: '/app/diet/meals/$mealType'
      path: '/diet/meals/$mealType'
      fullPath: '/app/diet/meals/$mealType'
      preLoaderRoute: typeof AppDietMealsMealTypeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/diet/foods/new': {
      id: '/app/diet/foods/new'
      path: '/diet/foods/new'
      fullPath: '/app/diet/foods/new'
      preLoaderRoute: typeof AppDietFoodsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppProfileRouteRouteChildren {
  AppProfileSettingsRoute: typeof AppProfileSettingsRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteRouteChildren: AppProfileRouteRouteChildren = {
  AppProfileSettingsRoute: AppProfileSettingsRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteRouteWithChildren = AppProfileRouteRoute._addFileChildren(
  AppProfileRouteRouteChildren,
)

interface AppStatsRouteChildren {
  AppStatsExercisesExerciseIdRoute: typeof AppStatsExercisesExerciseIdRoute
}

const AppStatsRouteChildren: AppStatsRouteChildren = {
  AppStatsExercisesExerciseIdRoute: AppStatsExercisesExerciseIdRoute,
}

const AppStatsRouteWithChildren = AppStatsRoute._addFileChildren(
  AppStatsRouteChildren,
)

interface AppRouteRouteChildren {
  AppProfileRouteRoute: typeof AppProfileRouteRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppStatsRoute: typeof AppStatsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDietAddRoute: typeof AppDietAddRoute
  AppDietSettingsRoute: typeof AppDietSettingsRoute
  AppSessionsTemplateIdRoute: typeof AppSessionsTemplateIdRoute
  AppSessionsNewRoute: typeof AppSessionsNewRoute
  AppWorkoutActiveRoute: typeof AppWorkoutActiveRoute
  AppWorkoutsWorkoutIdRoute: typeof AppWorkoutsWorkoutIdRoute
  AppDietIndexRoute: typeof AppDietIndexRoute
  AppExercisesIndexRoute: typeof AppExercisesIndexRoute
  AppFriendsIndexRoute: typeof AppFriendsIndexRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppPlanningIndexRoute: typeof AppPlanningIndexRoute
  AppPremiumIndexRoute: typeof AppPremiumIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
  AppDietFoodsNewRoute: typeof AppDietFoodsNewRoute
  AppDietMealsMealTypeRoute: typeof AppDietMealsMealTypeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRouteRoute: AppProfileRouteRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppStatsRoute: AppStatsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDietAddRoute: AppDietAddRoute,
  AppDietSettingsRoute: AppDietSettingsRoute,
  AppSessionsTemplateIdRoute: AppSessionsTemplateIdRoute,
  AppSessionsNewRoute: AppSessionsNewRoute,
  AppWorkoutActiveRoute: AppWorkoutActiveRoute,
  AppWorkoutsWorkoutIdRoute: AppWorkoutsWorkoutIdRoute,
  AppDietIndexRoute: AppDietIndexRoute,
  AppExercisesIndexRoute: AppExercisesIndexRoute,
  AppFriendsIndexRoute: AppFriendsIndexRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppPlanningIndexRoute: AppPlanningIndexRoute,
  AppPremiumIndexRoute: AppPremiumIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
  AppDietFoodsNewRoute: AppDietFoodsNewRoute,
  AppDietMealsMealTypeRoute: AppDietMealsMealTypeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CoachRouteRouteChildren {
  CoachIndexRoute: typeof CoachIndexRoute
  CoachProgramsProgramIdRoute: typeof CoachProgramsProgramIdRoute
  CoachAnalyticsIndexRoute: typeof CoachAnalyticsIndexRoute
  CoachClientsIndexRoute: typeof CoachClientsIndexRoute
  CoachProgramsIndexRoute: typeof CoachProgramsIndexRoute
  CoachValidateProductRenamesIndexRoute: typeof CoachValidateProductRenamesIndexRoute
}

const CoachRouteRouteChildren: CoachRouteRouteChildren = {
  CoachIndexRoute: CoachIndexRoute,
  CoachProgramsProgramIdRoute: CoachProgramsProgramIdRoute,
  CoachAnalyticsIndexRoute: CoachAnalyticsIndexRoute,
  CoachClientsIndexRoute: CoachClientsIndexRoute,
  CoachProgramsIndexRoute: CoachProgramsIndexRoute,
  CoachValidateProductRenamesIndexRoute: CoachValidateProductRenamesIndexRoute,
}

const CoachRouteRouteWithChildren = CoachRouteRoute._addFileChildren(
  CoachRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CoachRouteRoute: CoachRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ShareWorkoutShareTokenRoute: ShareWorkoutShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
